name: cactus_flutter
description: Cactus framework for running AI models locally on mobile devices
version: 0.0.1
homepage: https://github.com/cactus-compute/cactus

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.1
  path: ^1.8.0
  path_provider: ^2.0.11
  http: ^1.1.0
  dio: ^5.0.0
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.0
  json_serializable: ^6.6.0

flutter:
  plugin:
    platforms:
      android:
        package: com.cactus.flutter
        pluginClass: CactusFlutterPlugin
      ios:
        pluginClass: CactusFlutterPlugin 